### ISSUE TITLE
how to convert dynamic jade file which has partials, variables, loops , control statements already??

### ISSUE THREAD

**Issue by rahul9874563210** [Rastopyr/gulp-jade-hbs#1]

**Comment by Rastopyr** [comment]
Describe question in more detail, and add examples please

**Comment by LantosIstvan** [comment]
I think I have the same error:

``` shell
$ gulp
[11:41:11] Using gulpfile C:\www\node\jade-to-handlebars\gulpfile.js
[11:41:11] Starting 'templates'...
[11:41:11] Finished 'templates' after 16 ms
[11:41:11] Starting 'default'...
[11:41:11] Finished 'default' after 52 μs

events.js:154
      throw er; // Unhandled 'error' event
      ^
 TypeError: C:\www\node\jade-to-handlebars\views\layout.jade:21
    19|               ul.nav.nav-list
    20|                 li.nav-header categories
  > 21|                 - each cat in getCategories()
    22|                   li
    23|                     a(href=categoryURL(cat)) #{cat}
    24|                 li.nav-header tags

getCategories is not a function
    at eval (eval at <anonymous> (C:\www\node\jade-to-handlebars\node_modules\jade\lib\index.js:218:8), <anonymous>:105:15)
    at eval (eval at <anonymous> (C:\www\node\jade-to-handlebars\node_modules\jade\lib\index.js:218:8), <anonymous>:155:4)
    at eval (eval at <anonymous> (C:\www\node\jade-to-handlebars\node_modules\jade\lib\index.js:218:8), <anonymous>:247:22)
    at res (C:\www\node\jade-to-handlebars\node_modules\jade\lib\index.js:219:38)
    at DestroyableTransform.CompileJade [as _transform] (C:\www\node\jade-to-handlebars\node_modules\gulp-jade-hbs\index.js:34:50)
    at DestroyableTransform.Transform._read (C:\www\node\jade-to-handlebars\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\www\node\jade-to-handlebars\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\www\node\jade-to-handlebars\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\www\node\jade-to-handlebars\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (C:\www\node\jade-to-handlebars\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
```
